name: Build and validate

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            install-script: sudo apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++
          - os: macos-latest
            install-script: |
              brew install make automake libtool autoconf doxygen
              brew reinstall gfortran

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: ${{ matrix.install-script }}
    - name: Check for fortran compiler
      run: |
        which gfortran
        gfortran --version
    - name: Test gfortran
      run: |
        gfortran simple_fortran_program.f -o simple_fortran_program
        ./simple_fortran_program